# Bootstrap
Configuring parameters, loading libraries and connecting to database.

In [387]:
import sys, os
# This line allows us to import from the parent directory, which is where the 'src' folder is located.
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))
# These lines enable automatic reloading of modules in Jupyter, so that changes to the code are reflected without needing to restart the kernel.
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Libraries

In [388]:
!pip install psycopg2-binary
!pip install ipython-sql
!pip install "prettytable<3.0.0"
!pip install geopy
!pip install airportsdata

Requirement already satisfied: psycopg2-binary in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (2.9.11)
Requirement already satisfied: ipython-sql in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (0.5.0)
Requirement already satisfied: prettytable in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from ipython-sql) (2.5.0)
Requirement already satisfied: ipython in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from ipython-sql) (8.37.0)
Requirement already satisfied: sqlalchemy>=2.0 in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from ipython-sql) (2.0.48)
Requirement already satisfied: sqlparse in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from ipython-sql) (0.5.5)
Requirement already satisfied: six in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from sqlalchemy>=2.0->ipython-sql) (4.15.0)
Requirement already satisfied: decorator in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from ipython->ipython-sql) (5.2.1)
Requirement already satisfied: exceptiongroup in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from ipython->ipython-sql) (1.3.1)
Requirement already satisfied: jedi>=0.16 in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from ipython->ipython-sql) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from ipython->ipython-sql) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from ipython->ipython-sql) (2.20.0)
Requirement already satisfied: stack_data in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: wcwidth in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->ipython-sql) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.6)
Requirement already satisfied: ptyprocess>=0.5 in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from stack_data->ipython->ipython-sql) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from stack_data->ipython->ipython-sql) (3.0.1)
Requirement already satisfied: pure_eval in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from stack_data->ipython->ipython-sql) (0.2.3)
Requirement already satisfied: prettytable<3.0.0 in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (2.5.0)
Requirement already satisfied: wcwidth in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from prettytable<3.0.0) (0.6.0)
Requirement already satisfied: geopy in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (from geopy) (2.1)
Requirement already satisfied: airportsdata in /opt/miniconda3/envs/traveltida-rewards-program/lib/python3.10/site-packages (20260315)

External

In [389]:
import pandas as pd
import numpy as np
import airportsdata
from geopy.distance import geodesic

Project

In [390]:
from src.constants import SECONDS_IN_DAY, DAYOFWEEK_SATURDAY, DAYOFWEEK_SUNDAY
from src.utils import Config

## Configuration
Set here general paramenters

In [391]:
config = Config({
    'connection_string': 'postgresql://Test:bQNxVzJL4g6u@ep-noisy-flower-846766.us-east-2.aws.neon.tech/TravelTide?sslmode=require',
    'filter': {
        'initial_date': '2023-01-04',
        'min_sessions': 7,
    },
    'central_tendency_measure': 'mean',
    'save_csvs_path': '../data/aggregated/',
    'weekend_days': [DAYOFWEEK_SATURDAY, DAYOFWEEK_SUNDAY],
})

## Loading Datasets

In [392]:
%load_ext sql
%sql $config.connection_string
%config SqlMagic.autopandas = True

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [393]:
date_start = config.filter.initial_date
min_sessions = config.filter.min_sessions

In [394]:
%%sql df_selected_users <<
  SELECT user_id
  FROM sessions
  WHERE session_start >= :date_start
  GROUP BY user_id
  HAVING COUNT(*) > :min_sessions

 * postgresql://Test:***@ep-noisy-flower-846766.us-east-2.aws.neon.tech/TravelTide?sslmode=require
5998 rows affected.
Returning data to local variable df_selected_users

In [395]:
user_ids = tuple(df_selected_users.user_id.unique().tolist())

In [396]:
%%sql df_sessions <<
  SELECT *
  FROM sessions
  WHERE session_start >= :date_start
    AND user_id IN :user_ids

 * postgresql://Test:***@ep-noisy-flower-846766.us-east-2.aws.neon.tech/TravelTide?sslmode=require
49211 rows affected.
Returning data to local variable df_sessions

In [397]:
%%sql df_users <<
  SELECT *
  FROM users
  WHERE user_id IN :user_ids

 * postgresql://Test:***@ep-noisy-flower-846766.us-east-2.aws.neon.tech/TravelTide?sslmode=require
5998 rows affected.
Returning data to local variable df_users

In [398]:
trip_ids = tuple(df_sessions.trip_id.unique().tolist())

In [399]:
%%sql df_flights <<
  SELECT *
  FROM flights
  WHERE trip_id IN :trip_ids

 * postgresql://Test:***@ep-noisy-flower-846766.us-east-2.aws.neon.tech/TravelTide?sslmode=require
13717 rows affected.
Returning data to local variable df_flights

In [400]:
%%sql df_hotels <<
  SELECT *
  FROM hotels
  WHERE trip_id IN :trip_ids

 * postgresql://Test:***@ep-noisy-flower-846766.us-east-2.aws.neon.tech/TravelTide?sslmode=require
14313 rows affected.
Returning data to local variable df_hotels

In [401]:
df_sessions.set_index('session_id', inplace=True)
df_hotels.set_index('trip_id', inplace=True)
df_flights.set_index('trip_id', inplace=True)
df_users.set_index('user_id', inplace=True)

# Data Preprocessing

## Clean-up and Inconsistency Detection

### Users Table
* Is there something wrong with the distribution? (info + describe)
* Are nominal (gender) columns consistent?

In [402]:
df_users.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5998 entries, 23557 to 844489
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   birthdate         5998 non-null   object
 1   gender            5998 non-null   object
 2   married           5998 non-null   bool
 3   has_children      5998 non-null   bool
 4   home_country      5998 non-null   object
 5   home_city         5998 non-null   object
 6   home_airport      5998 non-null   object
 7   home_airport_lat  5998 non-null   object
 8   home_airport_lon  5998 non-null   object
 9   sign_up_date      5998 non-null   object
dtypes: bool(2), object(8)
memory usage: 433.4+ KB

> No missing values, but many columns need to be converted

In [403]:
cols_to_datetime = ['birthdate', 'sign_up_date']
df_users[cols_to_datetime] = df_users[cols_to_datetime].apply(pd.to_datetime, errors='coerce')
cols_to_numeric = ['home_airport_lat', 'home_airport_lon']
df_users[cols_to_numeric] = df_users[cols_to_numeric].apply(pd.to_numeric, errors='coerce')

In [404]:
# Checking `gender` values
df_users.gender.value_counts(normalize=True)

gender
F    0.882294
M    0.115872
O    0.001834
Name: proportion, dtype: float64

> We don't see the presence of invalid data for this column, but it's clearly inbalanced towards females.

### Sessions Table
* Is there something wrong with the distribution? (info + describe)
* Are there sessions with booking but no trip_id?
* Is there an inconsistency of session time? (end < start)

In [405]:
df_sessions.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49211 entries, 23557-3f6bd6be250e45959b33b808ac525df6 to 694265-74b2a86e73854afea04cd84b1a1d10e3
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   user_id                 49211 non-null  int64
 1   trip_id                 16702 non-null  object
 2   session_start           49211 non-null  datetime64[ns]
 3   session_end             49211 non-null  datetime64[ns]
 4   flight_discount         49211 non-null  bool
 5   hotel_discount          49211 non-null  bool
 6   flight_discount_amount  8282 non-null   object
 7   hotel_discount_amount   6205 non-null   object
 8   flight_booked           49211 non-null  bool
 9   hotel_booked            49211 non-null  bool
 10  page_clicks             49211 non-null  int64
 11  cancellation            49211 non-null  bool
dtypes: bool(5), datetime64[ns](2), int64(2), object(3)
memory usage: 3.2+ MB

In [406]:
# flight- and hotel_discount_amount were fetched as object, first we need to convert it
cols_to_numeric = ['flight_discount_amount', 'hotel_discount_amount']
df_sessions[cols_to_numeric] = df_sessions[cols_to_numeric].apply(pd.to_numeric, errors='coerce')

df_sessions.describe()

,user_id,session_start,session_end,flight_discount_amount,hotel_discount_amount,page_clicks
count,49211.000000,49211,49211,8282.000000,6205.000000,49211.000000
mean,545282.694946,2023-03-21 11:25:24.870191872,2023-03-21 11:28:32.122520320,0.139864,0.112192,17.588791
min,23557.000000,2023-01-04 00:01:00,2023-01-04 00:04:23,0.050000,0.050000,1.000000
25%,517119.000000,2023-02-05 22:31:30,2023-02-05 22:34:10.500000,0.100000,0.050000,6.000000
50%,540308.000000,2023-03-09 11:04:00,2023-03-09 11:06:35,0.100000,0.100000,13.000000
75%,573922.000000,2023-04-28 11:23:00,2023-04-28 11:25:11.500000,0.200000,0.150000,22.000000
max,844489.000000,2023-07-28 19:58:52,2023-07-28 20:08:52,0.600000,0.450000,566.000000
std,64640.047648,NaN,NaN,0.083914,0.062119,21.495987

In [407]:
# There is NO session with booking but not a trip_id associated
df_sessions[(df_sessions.flight_booked | df_sessions.hotel_booked) & df_sessions.trip_id.isna()]

Empty DataFrame
Columns: [user_id, trip_id, session_start, session_end, flight_discount, hotel_discount, flight_discount_amount, hotel_discount_amount, flight_booked, hotel_booked, page_clicks, cancellation]
Index: []

In [408]:
# There is No session with inconsistent time
df_sessions[df_sessions.session_end < df_sessions.session_start].head()

Empty DataFrame
Columns: [user_id, trip_id, session_start, session_end, flight_discount, hotel_discount, flight_discount_amount, hotel_discount_amount, flight_booked, hotel_booked, page_clicks, cancellation]
Index: []

The database does not have Foreign Key constraint for *trip_id*, let's check if all *trip_id*s in **session** are present in either **flights** or **hotels** and it's not a cancellation session.

In [409]:
# No inconsistency found here
trip_ids = df_flights.index.to_list() + df_hotels.index.to_list()
df_sessions[~df_sessions.trip_id.isna() & ~df_sessions.trip_id.isin(trip_ids) & ~df_sessions.cancellation]

Empty DataFrame
Columns: [user_id, trip_id, session_start, session_end, flight_discount, hotel_discount, flight_discount_amount, hotel_discount_amount, flight_booked, hotel_booked, page_clicks, cancellation]
Index: []

### Hotels Table
* Is there any strange value in the distribuition? (info + describe)
* Is there a check_out_time before check_in_time?

In [410]:
# Flagging cancelled trips
cancelled_trip_ids = df_sessions[df_sessions.cancellation].trip_id.to_list()
df_hotels['cancelled'] = df_hotels.index.isin(cancelled_trip_ids)
df_flights['cancelled'] = df_flights.index.isin(cancelled_trip_ids)
# Erase check-out time for cancelled hotels. Keep check-in as "intented booking date"
df_hotels.loc[df_hotels.cancelled, 'check_out_time'] = pd.NaT

In [411]:
df_hotels.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14313 entries, 204997-303a3759d5814673b7c60db793d46cdd to 640715-0e556808e625448aa48c0fd73759e7da
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   hotel_name          14313 non-null  object
 1   nights              14313 non-null  int64
 2   rooms               14313 non-null  int64
 3   check_in_time       14313 non-null  datetime64[ns]
 4   check_out_time      13896 non-null  datetime64[ns]
 5   hotel_per_room_usd  14313 non-null  object
 6   cancelled           14313 non-null  bool
dtypes: bool(1), datetime64[ns](2), int64(2), object(2)
memory usage: 1.3+ MB

In [412]:
# hotel_per_room_usd need conversion
df_hotels['hotel_per_room_usd'] = df_hotels['hotel_per_room_usd'].apply(pd.to_numeric, errors='coerce')

# Check columns distribuition and CT values
df_hotels.describe()

,nights,rooms,check_in_time,check_out_time,hotel_per_room_usd
count,14313.000000,14313.000000,14313,13896,14313.000000
mean,3.618319,1.194369,2023-04-05 01:14:59.827218688,2023-04-07 00:30:34.196891136,178.046112
min,-2.000000,1.000000,2023-01-05 11:00:00,2023-01-08 11:00:00,17.000000
25%,1.000000,1.000000,2023-02-15 11:00:00,2023-02-18 11:00:00,99.000000
50%,2.000000,1.000000,2023-03-21 12:10:12.720000,2023-03-24 11:00:00,148.000000
75%,5.000000,1.000000,2023-05-14 17:41:24,2023-05-16 11:00:00,223.000000
max,43.000000,4.000000,2024-07-17 00:33:41.625000,2024-07-29 11:00:00,1376.000000
std,3.755245,0.498269,NaN,NaN,118.567176

In [413]:
# Check hotel bookins with check-out before check-in
df_hotels_inconsistent = df_hotels[df_hotels.check_out_time < df_hotels.check_in_time]
df_hotels_inconsistent

,hotel_name,nights,rooms,check_in_time,check_out_time,hotel_per_room_usd,cancelled
trip_id,,,,,,,
510134-078127b930e543048dd0b4e546dc4df6,Aman Resorts - new york,0,1,2023-01-11 11:02:30.300,2023-01-11 11:00:00,168.0,False
507759-b67459329f5a418884443d574104bfdc,Choice Hotels - san diego,0,1,2023-01-15 11:18:33.750,2023-01-15 11:00:00,286.0,False
476714-f7d36ece6b46409cbe363123d363bd40,Banyan Tree - oklahoma city,0,2,2023-01-15 11:44:13.425,2023-01-15 11:00:00,294.0,False
509282-a2bf5b84091b47a8ab3f12c95f8dd863,Extended Stay - new york,-1,1,2023-01-10 15:51:29.790,2023-01-10 11:00:00,708.0,False
471717-544bc48c0aa84d799f652708b159bf36,Marriott - calgary,0,1,2023-01-17 11:26:56.400,2023-01-17 11:00:00,217.0,False
...,...,...,...,...,...,...,...
531771-16bedec565e347afb51f39c179fbd5c5,Radisson - toronto,0,4,2023-07-19 11:46:07.995,2023-07-19 11:00:00,336.0,False
671975-d89549deef7a4be4a4c02bf80198f6db,Accor - los angeles,-1,1,2023-07-10 14:44:02.220,2023-07-10 11:00:00,163.0,False
506250-134d680a8ca64d99aba801607c3ed32d,Radisson - san antonio,-1,1,2023-07-08 11:34:58.980,2023-07-07 11:00:00,161.0,False
510093-e71475580a7c4948ba8f13114a60fa30,Marriott - winnipeg,0,1,2023-07-30 11:45:27.810,2023-07-30 11:00:00,109.0,False
530724-935e71d36d5441028c6d61ac3b5e5606,Hyatt - chicago,-1,1,2023-07-26 12:53:27.870,2023-07-26 11:00:00,160.0,False

We can see that:
* _nights_ have a min=-2 (it contains values 0, -1 and -2)
* check_in- and out_time are inconsistent in 221 rows

Observing the data, we notice that all check_out_times are, regardless of the day, at 11am. Which seems to be a standard for the system.
Some checkouts happen on the same day of checkin, but as the system sets the checkout to 11am, the inconsistency happens in them.

As they are not flagged as cancelled, we'll assume the check-out date is wrong and we'll set as the flight return date-time.

In [414]:
from datetime import datetime, time

# Now we set check_out_time to 11:00 of the same day of the flight, assuming the system failed somehow when setting the correct check_out_time
for trip_id, row in df_hotels_inconsistent.iterrows():
    return_time = df_flights.loc[trip_id, 'return_time']
    df_hotels.loc[trip_id, 'check_out_time'] = pd.NA if pd.isna(return_time) else datetime.combine(return_time.date(), time(11,0,0))

Now we recalculate the nights column

In [415]:
fractional_days = (df_hotels['check_out_time'] - df_hotels['check_in_time']).dt.total_seconds() / SECONDS_IN_DAY
df_hotels['nights'] = np.round(fractional_days).astype('Int64')

### Flights Table
* Is there any strange value in the distribuition? (info + describe)
* Are there flights with return flag True but no return time set?
* Is there any inconsistency between the departure and arrival times for flights?

In [416]:
df_flights.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13717 entries, 659128-a02f1af346a34ee7be3a82d80e928e71 to 610806-0eaa44bb134f4fc29223575efdffdca1
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   origin_airport           13717 non-null  object
 1   destination              13717 non-null  object
 2   destination_airport      13717 non-null  object
 3   seats                    13717 non-null  int64
 4   return_flight_booked     13717 non-null  bool
 5   departure_time           13717 non-null  datetime64[ns]
 6   return_time              13120 non-null  datetime64[ns]
 7   checked_bags             13717 non-null  int64
 8   trip_airline             13717 non-null  object
 9   destination_airport_lat  13717 non-null  object
 10  destination_airport_lon  13717 non-null  object
 11  base_fare_usd            13717 non-null  object
 12  cancelled                13717 non-null  bool
dtypes: bool(2), datetime64[ns](2), int64(2), object(7)
memory usage: 1.8+ MB

In [417]:
# Some object columns need conversion to numeric
cols = ['destination_airport_lat', 'destination_airport_lon', 'base_fare_usd']
df_flights[cols] = df_flights[cols].apply(pd.to_numeric, errors='coerce')

df_flights.describe()

,seats,departure_time,return_time,checked_bags,destination_airport_lat,destination_airport_lon,base_fare_usd
count,13717.000000,13717,13120,13717.000000,13717.000000,13717.000000,13717.000000
mean,1.200044,2023-04-10 18:43:27.158999808,2023-04-15 00:15:25.243902720,0.582562,38.700888,-90.514338,490.700007
min,1.000000,2023-01-07 07:00:00,2023-01-08 07:00:00,0.000000,-37.008000,-157.927000,2.410000
25%,1.000000,2023-02-15 07:00:00,2023-02-18 16:00:00,0.000000,33.942000,-112.383000,198.530000
50%,1.000000,2023-03-22 09:00:00,2023-03-26 07:00:00,1.000000,39.872000,-87.752000,378.050000
75%,1.000000,2023-05-19 07:00:00,2023-05-23 07:00:00,1.000000,42.409000,-75.669000,591.080000
max,8.000000,2024-07-16 07:00:00,2024-07-30 16:00:00,8.000000,55.972000,174.792000,21548.040000
std,0.555145,NaN,NaN,0.657846,6.627433,29.031302,701.362388

In [418]:
# Are there flight bookings with return_flight_booked but no return_time set?
df_flights[df_flights.return_flight_booked & df_flights.return_time.isna()]

Empty DataFrame
Columns: [origin_airport, destination, destination_airport, seats, return_flight_booked, departure_time, return_time, checked_bags, trip_airline, destination_airport_lat, destination_airport_lon, base_fare_usd, cancelled]
Index: []

In [419]:
# Are there flight bookings with return_flight_booked = False but return_time set?
df_flights[~df_flights.return_flight_booked & ~df_flights.return_time.isna()]

Empty DataFrame
Columns: [origin_airport, destination, destination_airport, seats, return_flight_booked, departure_time, return_time, checked_bags, trip_airline, destination_airport_lat, destination_airport_lon, base_fare_usd, cancelled]
Index: []

In [420]:
# Are there flight bookings where the return time <= departure time?
df_flights_inconsistent = df_flights[df_flights.return_time <= df_flights.departure_time]
df_flights_inconsistent

,origin_airport,destination,destination_airport,seats,return_flight_booked,departure_time,return_time,checked_bags,trip_airline,destination_airport_lat,destination_airport_lon,base_fare_usd,cancelled
trip_id,,,,,,,,,,,,,
563201-4a0d959baece4b118b308a616a4fc5b5,LAX,new york,LGA,1,True,2023-03-30 07:00:00,2023-03-30 07:00:00,0,Delta Air Lines,40.640,-73.779,740.64,False
590473-11e07cdbe77a4e28a445861ed6776750,LGA,tucson,TUS,1,True,2023-04-01 09:00:00,2023-04-01 09:00:00,0,Air France,32.166,-110.883,634.32,False
612220-ff208986968c45c691d4d7d78f81de7d,LBB,new york,JFK,1,True,2023-04-04 08:00:00,2023-04-04 08:00:00,2,Austrian Airlines,40.640,-73.779,438.49,False
513826-1e0021d03640427ba802c9332841377b,BIF,philadelphia,PHL,1,True,2023-04-16 09:00:00,2023-04-16 09:00:00,0,American Airlines,39.872,-75.241,565.02,False
637633-6cb2fb8a5dd54c2992ab08e0649ad182,YKZ,san jose,SJC,1,True,2023-04-18 07:00:00,2023-04-18 07:00:00,0,United Airlines,37.362,-121.929,650.83,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
597946-d338333c029e4c5c9be093c65d52815b,ATL,philadelphia,PHL,1,True,2023-03-14 08:00:00,2023-03-14 08:00:00,1,JetBlue Airways,39.872,-75.241,181.83,False
582833-33be6f10bafd41318fb53907233a1044,YIP,toronto,YZD,4,True,2023-03-13 07:00:00,2023-03-13 07:00:00,1,Delta Air Lines,43.862,-79.370,282.00,False
604136-cde98f09b7724bdcbf7df42406bf17ee,YKZ,baltimore,BWI,2,True,2023-03-17 11:00:00,2023-03-17 11:00:00,0,Southwest Airlines,39.175,-76.668,204.66,False
541389-fccd0c44b69d4d5ea36e088c1873284c,YIP,san antonio,SKF,1,True,2023-03-22 07:00:00,2023-03-22 07:00:00,1,Ryanair,29.529,-98.279,301.64,False
518092-bc05154aa86f4129a6ed0b478486cb65,JFK,denver,DEN,1,True,2023-03-26 11:00:00,2023-03-26 11:00:00,1,Spirit Airlines,39.858,-104.667,454.41,False

We see there are 70 rows with inconsistent return time. Since we do not have a way to fix this value, we'll just drop all rows.

In [421]:
trip_ids = df_flights_inconsistent.index.to_list()
df_flights.drop(trip_ids, inplace=True)
df_sessions = df_sessions[~df_sessions.trip_id.isin(trip_ids)]

# Feature Engineering
Here we'll define some new features and calculate aggregations:

* Per Session:
  * `session_duration`: interval between session start and end, in minutes
  * `lead_time`: days booked before flight departure or hotel check-in

* Per Flight:
  * `total_flight_price`: base fare times seats
  * `trip_duration`: interval between departure and return flights, in days
  * `flight_distance_km`: Haversine distance between origin and destination airports
  * `cents_per_km_flown`: base fare, in cents, divided by flight distance
  * `weekdays_in_trip`: number of weekdays in that trip
  * `weekends_in_trip`: number of weekend days in that trip

* Per Hotel:
  * `total_hotel_price`: perce per room times rooms and nights

* Per User:
  * `age`: in years
  * `total_sessions`: count of session_ids
  * `total_trips`: count of trip_ids
  * `flight_bookings`: count of booked flights
  * `hotel_bookings`: count of booked flights
  * `combo_bookings`: count of bookings with both flight and hotel
  * `cancellations`: count of cancellations
  * `avg_page_clicks`: average page clicks per session
  * `avg_page_clicks_flight_booked`: average page clicks in sessions with a flight booked
  * `avg_page_clicks_hotel_booked`: average page clicks in sessions with a hotel booked
  * `avg_seats_booked`: average seats booked per trip
  * `avg_flight_amount`: average amount spent (in USD) per flight booking
  * `total_flight_amount`: sum of all amount spent booking flights
  * `avg_flight_discount`: average discount (in USD) received for flights
  * `total_flight_discount`: sum of all discounts (in USD) received for flights
  * `avg_cents_km_flown`: average price per km for booked flights
  * `avg_hotel_amount`: average amount spent (in USD) per hotel booking
  * `total_hotel_amount`: sum of all amount spent booking hotels
  * `avg_hotel_discount`: average discount (in USD) received for hotels
  * `total_hotel_discount`: sum of all discounts (in USD) received for hotels
  * `discount_sensitivity`: percentage of bookings done with discount
  * `avg_hotel_nights`: average number of nights per hotel stay
  * `total_hotel_nights`: sum of all nights for hotel bookings
  * `avg_checked_bags`: average number of bags checked per flight
  * `total_checked_bags`: sum of all bags checked in flights
  * `avg_distance_flown`: average distance flown per flight
  * `total_distance_flown`: sum of all distance flown
  * `pct_only_flight_booked`: percentage of flights booked without a hotel
  * `pct_only_hotel_booked`: percentage of hotels booked without a flight
  * `avg_trip_lead_time`: average lead time for trips in days
  * `avg_trip_duration`: average trip duration in days
  * `weekdays_travelled`: total number of weekdays on trips
  * `weekends_travelled`: total number of weekend days on trips (e.g. Sat+Sun = 2)
  * `weekends_proportion`: proportion of weekends travelled by all trip days

In [422]:
def merge_dfs():
  df = df_sessions.merge(df_users, on='user_id', how='left') \
                        .merge(df_flights, on='trip_id', how='left') \
                        .merge(df_hotels, on='trip_id', how='left')
  df.index = df_sessions.index
  return df

In [423]:
df_sessions.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49141 entries, 23557-3f6bd6be250e45959b33b808ac525df6 to 694265-74b2a86e73854afea04cd84b1a1d10e3
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   user_id                 49141 non-null  int64
 1   trip_id                 16632 non-null  object
 2   session_start           49141 non-null  datetime64[ns]
 3   session_end             49141 non-null  datetime64[ns]
 4   flight_discount         49141 non-null  bool
 5   hotel_discount          49141 non-null  bool
 6   flight_discount_amount  8273 non-null   float64
 7   hotel_discount_amount   6188 non-null   float64
 8   flight_booked           49141 non-null  bool
 9   hotel_booked            49141 non-null  bool
 10  page_clicks             49141 non-null  int64
 11  cancellation            49141 non-null  bool
dtypes: bool(5), datetime64[ns](2), float64(2), int64(2), object(1)
memory usage: 3.2+ MB

In [424]:
# Sessions
df = merge_dfs()
df_sessions['session_duration'] = (df_sessions.session_end - df_sessions.session_start).dt.total_seconds() / 60
df_sessions['trip_start'] = np.where(~df.departure_time.isna(), df.departure_time, df.check_in_time)
df_sessions['lead_time'] = (df_sessions.trip_start - df_sessions.session_start).dt.days

In [425]:
df_flights.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13647 entries, 659128-a02f1af346a34ee7be3a82d80e928e71 to 610806-0eaa44bb134f4fc29223575efdffdca1
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   origin_airport           13647 non-null  object
 1   destination              13647 non-null  object
 2   destination_airport      13647 non-null  object
 3   seats                    13647 non-null  int64
 4   return_flight_booked     13647 non-null  bool
 5   departure_time           13647 non-null  datetime64[ns]
 6   return_time              13050 non-null  datetime64[ns]
 7   checked_bags             13647 non-null  int64
 8   trip_airline             13647 non-null  object
 9   destination_airport_lat  13647 non-null  float64
 10  destination_airport_lon  13647 non-null  float64
 11  base_fare_usd            13647 non-null  float64
 12  cancelled                13647 non-null  bool
dtypes: bool(2), datetime64[ns](2), float64(3), int64(2), object(4)
memory usage: 1.3+ MB

In [426]:
# Convert the AirportsData library's dictionary to a DataFrame
df_airports = pd.DataFrame(airportsdata.load('IATA')).T[['lat', 'lon']]
# Merge origin airport's coordenate to dataframe
df_flights = df_flights.merge(df_airports, left_on='origin_airport', right_index=True) \
            .rename(columns={'lat': 'origin_airport_lat', 'lon': 'origin_airport_lon'})

# Flights
df_flights['total_flight_price'] = df_flights.base_fare_usd * df_flights.seats
df_flights['trip_duration'] = (df_flights.return_time - df_flights.departure_time).dt.days
df_flights['flight_distance_km'] = df_flights.apply(
    lambda x: geodesic(
        (x.origin_airport_lat, x.origin_airport_lon),
        (x.destination_airport_lat, x.destination_airport_lon)
    ).km,
    axis=1
)
df_flights['cents_per_km_flown'] = (df_flights.base_fare_usd * 100) / df_flights.flight_distance_km
# Calculate weekdays vs weekends travelled for each trip
for trip_id, flight in df_flights.iterrows():
    current_day = flight.departure_time
    weekdays_travelled = 0
    weekends_travelled = 0
    if flight.trip_duration > 0:
        for day in range(round(flight.trip_duration)):
            if current_day.weekday() in config.weekend_days:
                weekends_travelled += 1
            else:
                weekdays_travelled += 1
            current_day += pd.Timedelta(days=1)
        df_flights.loc[trip_id, 'weekdays_in_trip'] = weekdays_travelled
    df_flights.loc[trip_id, 'weekends_in_trip'] = weekends_travelled

In [427]:
# Hotels
df_hotels['total_hotel_price'] = df_hotels.hotel_per_room_usd * df_hotels.rooms

In [428]:
# Users
df = merge_dfs()
df_users['age'] = (pd.to_datetime('today') - df_users.birthdate).dt.days // 365.25
summary = df.assign(
    session_id = df.index,
    flight_booked = df.flight_booked & ~df.cancellation,
    hotel_booked = df.hotel_booked & ~df.cancellation,
    combo_booked = df.flight_booked & df.hotel_booked & ~df.cancellation,
    page_clicks_flight_booked = np.where(df.flight_booked & ~df.cancellation, df.page_clicks, np.nan),
    page_clicks_hotel_booked = np.where(df.hotel_booked & ~df.cancellation, df.page_clicks, np.nan),
    total_flight_amount = df.base_fare_usd * df.seats,
    booked_with_discount = np.where(df.flight_booked & (df.flight_discount > 0) | df.hotel_booked & (df.hotel_discount > 0), 1, 0),
    total_flight_discount = np.where(df.flight_booked,
                            df.flight_discount_amount * df.base_fare_usd * df.seats,
                            np.nan),
    total_hotel_amount = df.hotel_per_room_usd * df.rooms * df.nights,
    total_hotel_discount = np.where(df.hotel_booked,
                           df.hotel_discount_amount * df.hotel_per_room_usd * df.nights * df.rooms,
                           np.nan)
).groupby('user_id').agg(
    total_sesions = ('session_id', 'count'),
    total_trips = ('trip_id', 'nunique'),
    flight_bookings = ('flight_booked', 'sum'),
    hotel_bookings = ('hotel_booked', 'sum'),
    combo_bookings = ('combo_booked', 'sum'),
    cancellations = ('cancellation', 'sum'),
    avg_page_clicks = ('page_clicks', config.central_tendency_measure),
    avg_page_clicks_flight_booked = ('page_clicks_flight_booked', config.central_tendency_measure),
    avg_page_clicks_hotel_booked = ('page_clicks_hotel_booked', config.central_tendency_measure),
    avg_seats_booked = ('seats', config.central_tendency_measure),
    avg_flight_amount = ('total_flight_amount', config.central_tendency_measure),
    total_flight_amount = ('total_flight_amount', 'sum'),
    avg_flight_discount = ('total_flight_discount', config.central_tendency_measure),
    total_flight_discount = ('total_flight_discount', 'sum'),
    avg_cents_km_flown = ('cents_per_km_flown', config.central_tendency_measure),
    avg_hotel_amount = ('total_hotel_amount', config.central_tendency_measure),
    total_hotel_amount = ('total_hotel_amount', 'sum'),
    discount_sensitivity = ('booked_with_discount', 'mean'),
    avg_hotel_discount = ('total_hotel_discount', config.central_tendency_measure),
    total_hotel_discount = ('total_hotel_discount', 'sum'),
    avg_hotel_nights = ('nights', config.central_tendency_measure),
    total_hotel_nights = ('nights', 'sum'),
    avg_checked_bags = ('checked_bags', config.central_tendency_measure),
    total_checked_bags = ('checked_bags', 'sum'),
    avg_distance_flown = ('flight_distance_km', config.central_tendency_measure),
    total_distance_flown = ('flight_distance_km','sum'),
    avg_trip_lead_time = ('lead_time', config.central_tendency_measure),
    avg_trip_duration = ('trip_duration', config.central_tendency_measure),
    weekdays_travelled = ('weekdays_in_trip', 'sum'),
    weekends_travelled = ('weekends_in_trip', 'sum'),
)
summary['pct_only_flight_booked'] = (summary['flight_bookings'] - summary['combo_bookings']) / summary['total_trips']
summary['pct_only_hotel_booked'] = (summary['hotel_bookings'] - summary['combo_bookings']) / summary['total_trips']
summary['weekends_proportion'] = summary.weekends_travelled / (summary.weekdays_travelled + summary.weekends_travelled) 

df_user_stats = pd.concat([df_users, summary], axis=1)

# Saving Datasets

In [429]:
dfs = {
    'users': df_user_stats,
    'sessions': df_sessions,
    'flights': df_flights,
    'hotels': df_hotels,
}
for file, df in dfs.items():
  df.to_csv(config.save_csvs_path + f'{file}.csv', index=True)
print("CSVs saved successfully in data/clean/")

CSVs saved successfully in data/clean/